### ISSUE TITLE
Don't work on 4.0.33 of my setups if wrong

### ISSUE THREAD

**Issue by Kathou99** [zacharee/unifi-cam-proxy#5]
### Camera

Eufy & Reaolink

### Description

I got the error below in the additional informations

### How to reproduce

Run in docker compose with portainer

### Expected behaviour

To run

### Screenshots

![Capture d’écran 2024-07-16 180355](https://github.com/user-attachments/assets/dc87f5bd-c33c-4260-940a-a52eeb41449a)

### Additional information

 I can't make it work on 4.0.33

I run with docker-compose but I got these error(again and again)

```
Traceback (most recent call last):
  File "/usr/local/bin/unifi-cam-proxy", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.11/site-packages/unifi/main.py", line 174, in main
    loop.rununtilcomplete(run())
  File "/usr/local/lib/python3.11/asyncio/baseevents.py", line 653, in rununtil_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/unifi/main.py", line 167, in run
    cam = klass(args, logger)
          ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/unifi/cams/rtsp.py", line 14, in __init
    super().init(args, logger)
  File "/usr/local/lib/python3.11/site-packages/unifi/cams/base.py", line 48, in __init
    self._ssl_context.load_cert_chain(args.cert, args.cert)
IsADirectoryError: [Errno 21] Is a directory
```

Here is my docker compose, I redacted the ip and my password...

```
version: "3.5"
services:
  aquarium-2:
    restart: unless-stopped
    build: https://github.com/zacharee/unifi-cam-proxy.git
    volumes:
      - "./client.pem:/client.pem"
    command: >-
        unifi-cam-proxy
        --host IP OF NVR
        --mac '0417B65339DF'
        --cert /client.pem
        --token TOKEN-HERE
        rtsp -s 'RSTP INSIDE HERE'
```

**Comment by Radioactivebun0** [comment]
Im getting the same error.
